### ISSUE TITLE
Not compatible with latest acc

### ISSUE THREAD

**Issue by 9M2PJU** [CrazyBoyFeng/AccSettings#15]
Acc settings not compatible with latest acc

![Screenshot_2023-12-10-02-09-20-463_crazyboyfeng.accSettings.jpg](https://github.com/CrazyBoyFeng/AccSettings/assets/991353/1606773a-fec5-4f89-9bc3-460a9267c3b5)

**Comment by VR-25** [comment]
That message is just a reminder that the installed acc version is different from the one the app ships with. It doesn't necessarily mean "incompatible".

**Comment by fds39** [comment]
Thanks for the clarification. VR25, I confirm the incompatibility of ACC settings with your latest version of acc.
-the Daemon toggle button works once then locks the application >>Force close required
-the major function "Pause above" is not respected >> charging continues up to 100%.

Conclusion: DO NOT UPDATE the module in Magisk

For my old Samsung J3(2016), ACC 2022.6.4 is more than sufficient.
Thanks to VR-25 and CrazyBoyFeng, who I hope will return to maintaining his handy app for me.

**Comment by Releece** [comment]
I use it in combination with ACCA. This app still works to provide additional functionality for me (A13).

**Comment by Iey4iej3** [comment]
> the major function "Pause above" is not respected >> charging continues up to 100%.
> 
> Conclusion: DO NOT UPDATE the module in Magisk.

Are you sure that this is due to the incompatiblity, instead of a newly introduced bug in acc? The former seems improbable. Have you tried to set a charge limit in the terminal (after `su`)? If it does not work, then it should be a bug of new versions of acc.

**Comment by VR-25** [comment]
Config and acc -i formats have changed.
This app needs to catch up.

In order to move development forward, most legacy workarounds to support outdated fronteds must die.
