### ISSUE TITLE
Do i need to install acc manually?

### ISSUE THREAD

**Issue by anuraag488** [CrazyBoyFeng/AccSettings#4]
Since your app contains acc bundled is it required to install acc manually or your app will install it automatically?

**Comment by CrazyBoyFeng** [comment]
I designed it to automatically install or upgrade upon opening.&nbsp;
Did it not install as expected?

**Comment by anuraag488** [comment]
I have uninstalled other frontend app and acc magisk module before installing AccSetting. But it didn't offer me to install acc.

**Comment by CrazyBoyFeng** [comment]
I already know what happened, please wait for the fix. But since I've been traveling recently, you may need to wait some time.

**Comment by VR-25** [comment]
@CrazyBoyFeng, a major acc release will be up soon. Let's have the next AccSettings APK ship with it.

**Comment by VR-25** [comment]
https://github.com/VR-25/acc/releases/tag/v2022.2.3
